name: String extraction test
on:
  pull_request:
    paths:
      - 'packages/fxa-content-server/**'
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux packages
        run: |
          sudo apt update
          sudo apt install gettext -y
      - name: Clone l10n repository
        uses: actions/checkout@v3
        with:
          repository: mozilla/fxa-content-server-l10n
          path: "fxa-l10n"
      - name: Clone FxA code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          path: "fxa-code"
      - name: Extract gettext strings and flag for review
        run: |
          # Get hash from PR commit.
          echo "Extraction complete. Calculating new hashes..."
          NEW_HASHES="foo"

          # Get hash from base commit
          echo "Extraction complete. Calculating old hashes..."
          OLD_HASHES="bar"

          # Compare hashes
          if [ "$NEW_HASHES" = "$OLD_HASHES" ]
          then
            echo "No changes found."
          else
            echo "PR number: $PR_NUMBER"
            echo "Repo: $REPO_NAME"
            cd fxa-code
            gh repo set-default $REPO_NAME
            gh pr view $PR_NUMBER --json reviewRequests | jq -r ".reviewRequests[].name" | grep -q "fxa-l10n"
            if [ $? -ne 0 ]; then
                # Check if someone from the Localization Team already reviewed the PR.
                # Get the list of fxa-l10n reviewers, excluding non-l10n members
                L10N_REVIEWERS=$(gh api -H "Accept: application/vnd.github+json" /orgs/mozilla/teams/fxa-l10n/members | jq -r '(.[].login | select(. != "clouserw"))' | sort)
                # Get the list of reviewers who already approved the pull request
                PR_REVIEWERS=$(gh pr view $PR_NUMBER --json reviews | jq -r '.reviews[] | select(.state=="APPROVED") | .author.login' | sort)
                # Check intersection of the two lists
                L10N_APPROVERS=$(comm -12 <(echo "$L10N_REVIEWERS") <(echo "$PR_REVIEWERS"))
                if [ -z "$L10N_APPROVERS" ]; then
                    # Add mozilla/fxa-l10n as reviewer
                    echo "New changes found, adding reviewer."
                    gh pr edit $PR_NUMBER --add-reviewer mozilla/fxa-l10n
                else
                    echo "PR already reviewed by the localization team, skip adding reviewer."
                fi
            else
                echo "fxa-l10n already added, skip adding reviewer."
            fi
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.L10N_BUILDCHECK_GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          REPO_NAME: ${{ github.event.repository.full_name }}
