name: String extraction test
on:
  pull_request:
    paths:
      - 'packages/fxa-content-server/**'
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux packages
        run: |
          sudo apt update
      - name: Clone FxA code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: "fxa-code"
      - name: Extract gettext strings and flag for review
        run: |
          # Fake strings extraction to speed up debugging
          cd fxa-code
          NEW_HASHES="foo"
          OLD_HASHES="bar"

          # Compare hashes
          if [ "$NEW_HASHES" = "$OLD_HASHES" ]
          then
            echo "No changes found."
          else
            echo "Checking reviewers requested for PR #$PR_NUMBER in repository $REPO_NAME"
            echo "Test command"
            echo $(gh pr view $PR_NUMBER --json reviewRequests --repo $REPO_NAME)
            echo "Full command"
            echo $(gh pr view $PR_NUMBER --json reviewRequests --repo $REPO_NAME | jq -r ".reviewRequests[].name" | grep -q "fxa-l10n")
            gh pr view $PR_NUMBER --json reviewRequests --repo $REPO_NAME | jq -r ".reviewRequests[].name" | grep -q "fxa-l10n"
            if [ $? -ne 0 ]; then
                echo "fxa-l10n team not found in reviewers, checking if a localization EPM already reviewed the PR"
                # Check if someone from the Localization Team already reviewed the PR.
                # Get the list of fxa-l10n reviewers, excluding non-l10n members
                echo "Getting the list of localization EPMs in the fxa-l10n team"
                L10N_REVIEWERS=$(gh api -H "Accept: application/vnd.github+json" /orgs/mozilla/teams/fxa-l10n/members | jq -r '(.[].login | select(. != "clouserw"))' | sort)
                echo $L10N_REVIEWERS
                # Get the list of reviewers who already approved the pull request
                echo "Getting the list of reviewers for the PR"
                PR_REVIEWERS=$(gh pr view $PR_NUMBER --json reviews --repo $REPO_NAME | jq -r '.reviews[] | select(.state=="APPROVED") | .author.login' | sort)
                echo $PR_REVIEWERS
                # Check intersection of the two lists
                L10N_APPROVERS=$(comm -12 <(echo "$L10N_REVIEWERS") <(echo "$PR_REVIEWERS"))
                if [ -z "$L10N_APPROVERS" ]; then
                    # Add mozilla/fxa-l10n as reviewer
                    echo "New changes found, adding reviewer."
                    gh pr edit $PR_NUMBER --add-reviewer mozilla/fxa-l10n --repo $REPO_NAME
                else
                    echo "PR already reviewed by the localization team, skip adding reviewer."
                fi
            else
                echo "fxa-l10n already added, skip adding reviewer."
            fi
          fi
        env:
          GH_TOKEN: ${{ secrets.L10N_BUILDCHECK_GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          REPO_NAME: ${{ github.event.repository.full_name }}
